name: Deploy to Vertex AI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Set environment variables
      run: |
        echo "IMAGE_NAME=animal-classification" >> $GITHUB_ENV
        echo "MODEL_NAME=animal-classifier-model" >> $GITHUB_ENV
        echo "ENDPOINT_NAME=animal-classifier-endpoint" >> $GITHUB_ENV
        echo "REGION=us-central1" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:$GITHUB_SHA .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:$GITHUB_SHA

    - name: Deploy to Vertex AI
      run: |
        gcloud ai models create $MODEL_NAME \
          --region=$REGION \
          --container-image-uri=gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA \
          --project=$PROJECT_ID

        gcloud ai endpoints create $ENDPOINT_NAME \
          --region=$REGION \
          --project=$PROJECT_ID

        gcloud ai endpoints deploy-model $ENDPOINT_NAME \
          --region=$REGION \
          --model=$MODEL_NAME \
          --project=$PROJECT_ID
